config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :users, only: [:destroy, :show, :index]
    resources :posts, only: [:destroy, :index]
    resources :dashboards, only: [:index, :create,]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :posts, only: [:index, :new, :destroy, :create]
  resources :lists, only: [:new, :destroy, :create]
  resources :training_menus, only: [:new, :destroy, :create]
  resources :trainings, only: [:show, :new, :destroy, :index, :create, :update] do
    collection do
      get :new_menu
      post :new_menu
      get :new_detail
      post :new_detail
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :trainings
  has_many :training_menus
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :list
  belongs_to :training_menu
  

  def part
    list.part
  end
  
  def item
    training_menu.item
  end
  
end

app/models/training_list.rb
class TrainingList < ApplicationRecord
  belongs_to :training_menu
end

app/models/training_menu.rb
class TrainingMenu < ApplicationRecord
  has_many :trining_list
  belongs_to :list
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :trainings, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :training_menus, dependent: :destroy
  
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/funny_02.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top], unless: :admin_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

 private

 def admin_controller?
   self.class.module_parent_name == 'Admin'
 end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    @list.save
    redirect_to new_training_menu_path
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to trainings_path
  end

  private

  def list_params
    params.require(:list).permit(:part)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end



  def destroy
    post = Post.find(params[:id])
    user = post.user
    post.destroy
    redirect_to user_path(user)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/training_menus_controller.rb
class TrainingMenusController < ApplicationController
  def new
    @menu = TrainingMenu.new
    @lists = current_user.lists
  end

  def create
    @menu = TrainingMenu.new(training_menu_params)
    @menu.user = current_user
    @menu.save
    redirect_to trainings_path
  end

  def destroy
    training = TrainingMenu.find(params[:id])
    training.destroy
    redirect_to trainings_path
  end



  private

  def training_menu_params
    params.require(:training_menu).permit(:item, :list_id)
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def show
    @training = Training.find(params[:id])
  end

  def index
    @training = Training.new
    @lists = current_user.lists
  end

  def new
    @training = Training.new(training_date: Date.today)
    @lists = current_user.lists
    @menus = current_user.training_menus
  end

  def new_menu
    @training = Training.new(training_params)
    @training.training_date = Date.today
    @list = List.find(training_params[:list_id])
    @menus = @list.training_menus
  end

  def new_detail
    @training = Training.new
    @list = List.find(params[:training][:list_id])
    @training_menu = TrainingMenu.find(params[:training][:training_menu_id])

  end

  def create
    @training = Training.new(training_params)
    @training.user_id = current_user.id
    @training.save
    redirect_to trainings_path
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to trainings_path
  end

  def update
    @training = Training.find(params[:id])
    @training.update(training_params)
    redirect_to trainings_path
  end

  private

  def training_params
    params.require(:training).permit(:menu, :training_date, :list_id, :item, :training_menu_id, :weight, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :goal, :profile_image)
  end
end

app/helpers/admin/training_helper.rb
module Admin::TrainingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/part_helper.rb
module PartHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/training_lists_helper.rb
module TrainingListsHelper
end

app/helpers/training_menus_helper.rb
module TrainingMenusHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/trainings/index.html.erb
<h3>トレーニング一覧</h3>
<table class="table">
  <thead>
    <tr>
      <th>
        <% current_user.trainings.each_with_index do |training,idx| %>
        <% if idx == 0 %>
          <%= l training.training_date %>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= link_to "変更", training_path(training) %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<h3>トレーニングメニュー一覧</h3>

<table class="table">
  <% @lists.each do |list| %>
    <thead>
      <tr>
        <th class="d-flex p-2">
          <h4 class="pr-3"><%= list.part %></h4>
          <%= button_to "削除", list_path(list), method: :delete %>
        </th>
      </tr>
    </thead>


    <tbody>
      <% list.training_menus.each do |menu| %>
        <tr>
          <td>
            <%= menu.item %>
          </td>
          <td>
            <%= form_with model: @training, url: new_detail_trainings_path do |f| %>
              <%= f.hidden_field :training_date, value: Date.current %>
              <%= f.hidden_field :training_menu_id, value: menu.id %>
              <%= f.hidden_field :list_id, value: list.id %>
              <%= f.submit "鍛える" %>
            <% end %>
          </td>
          <td>
            <%= button_to "削除", training_menu_path(menu), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

<%= link_to "部位の追加", new_list_path %>
<%= link_to "種目の追加", new_training_menu_path %>

app/views/trainings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 pt-5 mx-auto">
      <%= form_with model: @training, url: new_menu_trainings_path do |f| %>
        <div class="form-group">
          <p>種目選択</p>
          <%= f.collection_select :list_id, @lists, :id, :part, {}, {} %>
          <%= f.submit "次へ" %>          
        </div>
      <% end %>
      <div class="col"><%= link_to "部位の追加", new_list_path %></div>
      <div class="col"><%= link_to "種目の追加", new_training_menu_path %></div>
      <div class="col"><%= link_to "一覧", trainings_path %></div>
    </div>
  </div>
</div>

app/views/trainings/new_2.html.erb
<%= form_with model: @training, url: trainings_path do |f| %>
  <%= f.text_field :training_date %>
  <%= f.collection_select :training_menu_id, @menus, :id, :item, {}, {} %>
  <%= f.hidden_field :list_id %>
  <%= f.submit "追加" %>
<% end %>

<%= link_to "部位の追加", new_list_path %>
<%= link_to "種目の追加", training_menus_new_path %>

app/views/trainings/new_detail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 pt-5 mx-auto">
      <p>部位:<%= @list.part %></p>
      <p>種目:<%= @training_menu.item %></p>
      <%= form_with model: @training, url: trainings_path, method: :post do |f| %>
        <%= f.hidden_field :training_date, value: Date.current %>
        <%= f.hidden_field :training_menu_id, value: @training_menu.id %>
        <%= f.hidden_field :list_id, value: @list.id %>
        <p>重量:<%= f.number_field :weight %></p>
        <p>回数:<%= f.number_field :body %></p>
        <p><%= f.submit "追加" %></p>
      <% end %>      
    </div>
  </div>
</div>

app/views/trainings/new_menu.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 pt-5 mx-auto">
      <%= form_with model: @training, url: new_detail_trainings_path do |f| %>
        <div class="form-group">
          <%= f.text_field :training_date %>
          <%= f.collection_select :training_menu_id, @menus, :id, :item, {}, {} %>
          <%= f.hidden_field :list_id %>
          <%= f.submit "次へ" %>
        </div>
      <% end %>
      <div class="col"><%= link_to "部位の追加", new_list_path %></div>
      <div class="col"><%= link_to "種目の追加", new_training_menu_path %></div>
    </div>
  </div>
</div>

app/views/trainings/show.html.erb
<div calss="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 pt-5 mx-auto">
      <p>トレーニング日:<%= @training.training_date %></p>
      <p>部位:<%= @training.part %></p>
      <p>種目:<%= @training.item %></p>
        <%= form_with model: @training, url: training_path(@training), method: :patch do |f| %>
          <p>重量:<%= f.number_field :weight %></p>
          <p>回数:<%= f.number_field :body %></p>
          <p><%= f.submit "更新" %></p>
        <% end %>
        <%= button_to "削除" ,training_path(@training), method: :delete %>
    </div>
  </div>
</div>