config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :users, only: [:destroy, :show, :index]
    resources :posts, only: [:destroy, :index]
    resources :dashboards, only: [:index, :create,]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :posts, only: [:index, :new, :destroy, :create]
  resources :lists, only: [:new, :destroy, :create]
  resources :training_menus, only: [:new, :destroy, :create]
  resources :trainings, only: [:show, :new, :destroy, :index, :create, :update] do
    collection do
      get :new_menu
      post :new_menu
      get :new_detail
      post :new_detail
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :trainings
  has_many :training_menus
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :list
  belongs_to :training_menu
  

  def part
    list.part
  end
  
  def item
    training_menu.item
  end
  
end

app/models/training_list.rb
class TrainingList < ApplicationRecord
  belongs_to :training_menu
end

app/models/training_menu.rb
class TrainingMenu < ApplicationRecord
  has_many :trining_list
  belongs_to :list
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :trainings, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :training_menus, dependent: :destroy
  
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/funny_02.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    @list.save
    redirect_to new_training_menu_path
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to trainings_path
  end

  private

  def list_params
    params.require(:list).permit(:part)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end



  def destroy
    post = Post.find(params[:id])
    user = post.user
    post.destroy
    redirect_to user_path(user)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :goal, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/part_helper.rb
module PartHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/training_lists_helper.rb
module TrainingListsHelper
end

app/helpers/training_menus_helper.rb
module TrainingMenusHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Meshiterro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matyoclar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/4252c4d753.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
          <div class="container">
            <div class="row">
              <div class="col-3">
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </div>
              <div class="col-3">
                <li>
                  <%= link_to "マイページ", user_path(current_user) %>
                </li>
              </div>
              <div class="col-3">
                <li>
                  <%= link_to "目標設定", edit_user_path(current_user) %>
                </li>
              </div>
              <div class="col-3">
                <li>
                  <%= link_to "トレーニング", new_training_path %>
                </li>
              </div>
              <div class="col-3">
                 <li>
                  <%= link_to "筋トレ一覧", trainings_path %>
                </li>
              </div>
              <div class="col-3">
                <li>
                  <%= link_to "投稿一覧", posts_path %>
                </li>
              </div>
            </div>
          </div>
        </nav>
      <% end %>
    </header>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>